source: ps-tool Browse v1.0.0
observed_display:
  line_count: "15/15 lines"
  columns:
    - "#"
    - CODE
    - NAME
    - WCF ADDRESS
environments:
  - index: 1
    code: BB
    name: "BB (Main Prod)"
    wcf_address: "np12971565bbp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 2
    code: DV
    name: "DV (PSO env DEV)"
    wcf_address: "nd29201564dvp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 3
    code: DZ
    name: "DZ (Quantum env DEV)"
    wcf_address: "nd29201564dzp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 4
    code: P1
    name: "P1 (Cloud Data Sourcing Prod)"
    wcf_address: "np3e791565p1p1.ubscloud-prod.msad.ubs.net:9001"
  - index: 5
    code: PA
    name: "PA (Secondary Prod)"
    wcf_address: "np3e791565pap2.ubscloud-prod.msad.ubs.net:9001"
  - index: 6
    code: PB
    name: "PB (to be decommissioned)"
    wcf_address: "np3e791565pbp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 7
    code: PY
    name: "PY (Pillar 2 Prod)"
    wcf_address: "np3e791565pyp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 8
    code: U1
    name: "U1 (Cloud Data Sourcing UAT)"
    wcf_address: "npb14716831u1p1.ubscloud-prod.msad.ubs.net:9001"
  - index: 9
    code: U5
    name: "U5 (UAT)"
    wcf_address: "npb14716831u5p1.ubscloud-prod.msad.ubs.net:9001"
  - index: 10
    code: UW
    name: "UW (Main UAT Secondary)"
    wcf_address: "np405216831uwp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 11
    code: UX
    name: "UX (Main UAT Primary)"
    wcf_address: "np405216831uxp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 12
    code: UZ
    name: "UZ (Interactive UAT)"
    wcf_address: "np405216831uzp2.ubscloud-prod.msad.ubs.net:9001"
  - index: 13
    code: XY
    name: "XY (PIE)"
    wcf_address: "nd29201564xyp1.ubscloud-prod.msad.ubs.net:9001"
  - index: 14
    code: XZ
    name: "XZ (PIE)"
    wcf_address: "nd29201564xzp1.ubscloud-prod.msad.ubs.net:9001"
